import { DepartmentResponse } from '@api/deparment/interface';

export const departmentListDummy: DepartmentResponse[] = [
  {
    id: 1,
    name: 'IT',
    description: 'Phòng it',
    address: '47 Điện Biên Phủ',
    company_id: 1,
    users: [
      {
        id: 1,
        avatar: 'https://picsum.photos/300/300',
        contacts: '',
        department_id: 1,
        email: 'user1@email.com',
        first_name: 'user1',
        last_name: 'user1',
        identity: 'user1',
        mail_storage: 'sdf',
        manager: 1,
        password: '',
        phone_number: '1',
        position: 'IT',
        role: '',
        role_id: 1,
        user_id: 1,
      },
      {
        id: 2,
        avatar: '',
        contacts: '',
        department_id: 2,
        email: 'user2@email.com',
        first_name: 'user2',
        last_name: 'user2',
        identity: 'user2',
        mail_storage: 'sdf',
        manager: 2,
        password: '',
        phone_number: '2',
        position: 'IT',
        role: '',
        role_id: 2,
        user_id: 2,
      },
      {
        id: 3,
        avatar: '',
        contacts: '',
        department_id: 3,
        email: 'user3@email.com',
        first_name: 'user3',
        last_name: 'user3',
        identity: 'user3',
        mail_storage: 'sdf',
        manager: 3,
        password: '',
        phone_number: '3',
        position: 'IT',
        role: '',
        role_id: 3,
        user_id: 3,
      },
      {
        id: 4,
        avatar: '',
        contacts: '',
        department_id: 4,
        email: 'user4@email.com',
        first_name: 'user4',
        last_name: 'user4',
        identity: 'user4',
        mail_storage: 'sdf',
        manager: 4,
        password: '',
        phone_number: '4',
        position: 'IT',
        role: '',
        role_id: 4,
        user_id: 4,
      },
    ],
  },
  {
    id: 2,
    name: 'FE',
    description: 'Phòng FE',
    address: '47 Điện Biên Phủ',
    company_id: 1,
    users: [
      {
        id: 5,
        avatar: '',
        contacts: '',
        department_id: 5,
        email: 'user5@email.com',
        first_name: 'user2',
        last_name: 'user5',
        identity: 'user5',
        mail_storage: 'sdf',
        manager: 1,
        password: '',
        phone_number: '5',
        position: 'IT',
        role: '',
        role_id: 1,
        user_id: 5,
      },
    ],
  },
  {
    id: 3,
    name: 'HR',
    description: 'Phòng it',
    address: '47 Điện Biên Phủ',
    company_id: 1,
    users: [
      {
        id: 10,
        avatar: '',
        contacts: '',
        department_id: 3,
        email: 'user10@email.com',
        first_name: 'user10',
        last_name: 'user10',
        identity: 'user10',
        mail_storage: 'sdf',
        manager: 1,
        password: '',
        phone_number: '10',
        position: 'HR',
        role: '',
        role_id: 1,
        user_id: 3,
      },
    ],
  },
];
