const Permission = Object.freeze({
  // FLUTTER PERMISSIONS
  WRITE_EXTERNAL_STORAGE: 'WRITE_EXTERNAL_STORAGE',
  INTERNET: 'INTERNET',
  WAKE_LOCK: 'WAKE_LOCK',
  READ_CONTACTS: 'READ_CONTACTS',
  WRITE_CONTACTS: 'WRITE_CONTACTS',
  VIBRATE: 'VIBRATE',
  FOREGROUND_SERVICE: 'FOREGROUND_SERVICE',
  CAMERA: 'CAMERA',
  UPLOAD: 'UPLOAD',
  RECORD_AUDIO: 'RECORD_AUDIO',
  ACCESS_NETWORK_STATE: 'ACCESS_NETWORK_STATE',
  CHANGE_NETWORK_STATE: 'CHANGE_NETWORK_STATE',
  MODIFY_AUDIO_SETTINGS: 'MODIFY_AUDIO_SETTINGS',
  ACCESS_FINE_LOCATION: 'ACCESS_FINE_LOCATION',
  ACCESS_COARSE_LOCATION: 'ACCESS_COARSE_LOCATION',
  READ_CALL_LOG: 'READ_CALL_LOG',
  QR_CORE: 'QR_CORE',
  IMPORT_WALLET_URL: 'IMPORT_WALLET_URL',
  IMPORT_WALLET_QR_CODE: 'IMPORT_WALLET_QR_CODE',
  SEND_SEED_PHRASE: 'SEND_SEED_PHRASE',
  TAKE_A_PICTURE: 'TAKE_A_PICTURE',
  CHOOSE_GALLERY: 'CHOOSE_GALLERY',
  // IBE PERMISSIONs
  CLIPBOARD: 'CLIPBOARD',
  USER_PROFILE: 'USER_PROFILE',
  NOTIFICATION: 'NOTIFICATION',
});

export default Permission;
